dist: xenial

language: python

matrix:
  include:
    - python: "3.7"
      env: TEST_LINT=yes

    - python: "3.6"

env:
  global:
    - PIPENV_VERBOSITY=-1

install:
  - bash .travis/install.sh

script:
  - bash .travis/script.sh
