language: python

python:
  - 3.6

install:
  - pip install -r requirements/ci.txt
  - for f in project/*.dev.example.py; do cp $f project/`basename $f .dev.example.py`.py; done

script:
  # Linter tests
  - flake8
  - mypy --ignore-missing-imports .
  - doc8 README.rst

  # Do migrations
  - ./manage.py migrate

  # Check if model changes are missing migrations
  - ./manage.py makemigrations --dry-run --check

  # Test features
  - ./manage.py test
