[tool.black]
target-version = ["py36"]
exclude = '''
(
  /(
      \.cache
    | \.eggs
    | \.git
    | \.mypy_cache
    | \.packages
    | \.pip
    | \.tox
    | \.venv.*
    | \.virtualenv.*
    | \.wheels
    | _build
    | build
    | dist
  )/
)
'''
